version: '3.8'
services:
  postgres:
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
